apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway-sse
  labels:
    cloud.googleapis.com/location: asia-east1
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/sessionAffinity: "true"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 3600
      containers:
        - image: gcr.io/PROJECT_ID/gateway-sse:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
          env:
            - name: RUST_LOG
              value: info
            - name: GCP_PROJECT
              valueFrom:
                secretKeyRef:
                  name: GCP_PROJECT
                  key: latest
            - name: PUBSUB_SUBSCRIPTION
              valueFrom:
                secretKeyRef:
                  name: PUBSUB_SUBSCRIPTION
                  key: latest
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
            timeoutSeconds: 3
